spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: spring-cloud-proudcer-DEPA-dev	

---  
server:
  port: 8001
spring:
  profiles: test
  application:
    name: spring-cloud-proudcer-DEPA-test

